#!/usr/bin/env python3
# Build the ternary search tree (TST) used by parser.asm to map free-function
# builtin names → impl-address. The 6502 walker reads the input string
# right-to-left (it lets the loop test end-of-input via `dey; bmi` rather than
# a separate compare against length), so names are inserted with characters in
# reversed order.
#
# Output is a KickAssembler include with five parallel SoA arrays, indexed by
# 1-byte node id, plus a dense impl-address payload table:
#
#   tst_char[i]    discriminator char at node i
#   tst_lt[i]      left-child node index, or 0 = "no child"
#   tst_eq[i]      eq-child  node index, or 0 = "no child"
#   tst_gt[i]      right-child node index, or 0 = "no child"
#   tst_payload[i] 0 if node is non-terminal, else 1-based index into tst_impl_*
#   tst_impl_lo / tst_impl_hi   impl-address per registered name
#
# The 0-as-"no child" sentinel doubles as "root index". A root cannot be its
# own child (no cycles in a tree), so the dual use never collides.
#
# Usage: build_tst.py <output.asm>

from __future__ import annotations

import sys
from pathlib import Path

# (admiral-source name, kickass impl label).
# Insertion order shapes the tree — kept in source-file order for now.
BUILTINS = [
    ("len",   "builtin_len"),
    ("range", "builtin_range"),
    ("bool",  "builtin_bool"),
    ("abs",   "builtin_abs"),
    ("chr",   "builtin_chr"),
    ("ord",   "builtin_ord"),
    ("type",  "builtin_type"),
    ("int",   "builtin_int"),
    ("float", "builtin_float"),
    ("str",   "builtin_str"),
    ("id",    "builtin_id"),
    ("cmp",   "builtin_cmp"),
    ("hex",   "builtin_hex"),
    ("repr",  "builtin_repr"),
    ("sort",  "builtin_sort"),
    ("rnd",   "builtin_rnd"),
]


class Node:
    __slots__ = ("char", "lt", "eq", "gt", "payload", "idx")

    def __init__(self, char: str) -> None:
        self.char = char
        self.lt: Node | None = None
        self.eq: Node | None = None
        self.gt: Node | None = None
        self.payload: str | None = None
        self.idx: int = -1


def insert(root: Node | None, chars: list[str], i: int, payload: str) -> Node:
    if root is None:
        root = Node(chars[i])
    if chars[i] < root.char:
        root.lt = insert(root.lt, chars, i, payload)
    elif chars[i] > root.char:
        root.gt = insert(root.gt, chars, i, payload)
    elif i + 1 < len(chars):
        root.eq = insert(root.eq, chars, i + 1, payload)
    else:
        if root.payload is not None:
            raise ValueError(f"duplicate name → payload {payload}")
        root.payload = payload
    return root


def dfs_assign(root: Node) -> list[Node]:
    nodes: list[Node] = []

    def walk(n: Node | None) -> None:
        if n is None:
            return
        n.idx = len(nodes)
        nodes.append(n)
        walk(n.lt)
        walk(n.eq)
        walk(n.gt)

    walk(root)
    return nodes


def lookup(root: Node, name: str) -> str | None:
    """Reference TST walk used to verify the built tree before emit."""
    chars = list(reversed(name))
    if not chars:
        return None
    n: Node | None = root
    i = 0
    while n is not None:
        c = chars[i]
        if c < n.char:
            n = n.lt
        elif c > n.char:
            n = n.gt
        else:
            i += 1
            if i == len(chars):
                return n.payload
            n = n.eq
    return None


def fmt_chars(values: list[str]) -> str:
    # Emit ASCII byte values as hex literals: KickAssembler's default text
    # encoding is screencode/PETSCII, so `'n'` would assemble to $0E or $4E,
    # not $6E. Hex bytes are unambiguous.
    return ", ".join(f"${ord(c):02X}" for c in values)


def fmt_ints(values: list[int]) -> str:
    return ", ".join(str(v) for v in values)


def emit(nodes: list[Node], names_in_order: list[tuple[str, str]],
        output_path: Path) -> None:
    payload_for_label: dict[str, int] = {}
    payloads: list[str] = []
    for _, label in names_in_order:
        payloads.append(label)
        payload_for_label[label] = len(payloads)  # 1-based

    if len(nodes) > 255:
        raise ValueError(f"too many TST nodes ({len(nodes)}) for 1-byte indexing")

    chars = [n.char for n in nodes]
    lt    = [n.lt.idx if n.lt else 0 for n in nodes]
    eq    = [n.eq.idx if n.eq else 0 for n in nodes]
    gt    = [n.gt.idx if n.gt else 0 for n in nodes]
    pay   = [payload_for_label[n.payload] if n.payload else 0 for n in nodes]

    lines = [
        "// Auto-generated by tools/build_tst.py — do not edit by hand.",
        "// Builtin-name TST: 6502 walks the input string right-to-left, so",
        "// names were inserted with characters in reversed order. Sentinel 0",
        "// = no child (root is at index 0; root is never anyone's child).",
        "",
        f"// {len(nodes)} nodes, {len(payloads)} payloads",
        "",
        "tst_char:",
        f"    .byte {fmt_chars(chars)}",
        "tst_lt:",
        f"    .byte {fmt_ints(lt)}",
        "tst_eq:",
        f"    .byte {fmt_ints(eq)}",
        "tst_gt:",
        f"    .byte {fmt_ints(gt)}",
        "tst_payload:",
        f"    .byte {fmt_ints(pay)}",
        "",
        "// payload index is 1-based (0 reserved for non-terminals); subtract 1",
        "// before reading these tables.",
        "tst_impl_lo:",
        "    .byte " + ", ".join(f"<{lbl}" for lbl in payloads),
        "tst_impl_hi:",
        "    .byte " + ", ".join(f">{lbl}" for lbl in payloads),
        "",
    ]
    output_path.write_text("\n".join(lines))


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: build_tst.py <output.asm>", file=sys.stderr)
        return 2
    out_path = Path(sys.argv[1])

    root: Node | None = None
    for name, label in BUILTINS:
        chars = list(reversed(name))
        root = insert(root, chars, 0, label)
    assert root is not None

    # Sanity: every registered name resolves through the built tree to its
    # own label, and a few negative cases miss.
    for name, label in BUILTINS:
        got = lookup(root, name)
        if got != label:
            raise SystemExit(f"self-check failed: {name!r} → {got}, expected {label}")
    for negative in ["", "le", "lens", "ranges", "z", "rang"]:
        if lookup(root, negative) is not None:
            raise SystemExit(f"self-check failed: {negative!r} should miss")

    nodes = dfs_assign(root)
    emit(nodes, BUILTINS, out_path)
    print(f"build_tst.py: wrote {out_path} ({len(nodes)} nodes, "
          f"{len(BUILTINS)} payloads)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
