#!/usr/bin/env python3
"""Assemble tools/gfx.asm with KickAssembler and generate the graphics-mode
extension libraries examples/{text,hires,mc}.admiral, embedding each routine's
machine code as a \\xNN CALL string.

Each routine in gfx.asm is delimited by its label and a matching <NAME>_END
label. Run after editing gfx.asm:  python3 tools/gfx_pack.py
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KICK = os.path.join(os.path.expanduser("~"), "bin", "KickAssembler", "KickAss.jar")
SRC = os.path.join(ROOT, "tools", "gfx.asm")
OUTDIR = os.path.join(ROOT, "build")
EXAMPLES = os.path.join(ROOT, "examples")

# (label, end-label) — end defaults to label + "_END".
END = {"GFX_CLS": "GFX_CLS_END"}

# DRAW is an Admiral-level Bresenham line that calls the native PLOT primitive
# (high-level loop, native per-point plot). _PLOTCALL is the per-point call
# (with the mode's extra args). Generated as a plain Admiral method body.
def _draw_body(plotcall: str) -> str:
    return "\n".join([
        "TX = X1 - X0",
        "IF TX < 0:",
        "  DX = 0 - TX",
        "  SX = 0 - 1",
        "ELSE:",
        "  DX = TX",
        "  SX = 1",
        "TY = Y1 - Y0",
        "IF TY < 0:",
        "  DY = TY",
        "  SY = 0 - 1",
        "ELSE:",
        "  DY = 0 - TY",
        "  SY = 1",
        "ER = DX + DY",
        "WHILE TRUE:",
        "  " + plotcall,
        "  IF X0 == X1:",
        "    IF Y0 == Y1:",
        "      BREAK",
        "  E2 = ER + ER",
        "  IF E2 >= DY:",
        "    ER = ER + DY",
        "    X0 = X0 + SX",
        "  IF E2 <= DX:",
        "    ER = ER + DX",
        "    Y0 = Y0 + SY",
    ])

HIRES_DRAW = _draw_body("ME.PLOT(X=X0, Y=Y0)")
MC_DRAW = _draw_body("ME.PLOT(X=X0, Y=Y0, INK=INK)")

# Per output file: header comment, dict var, and the (method, code-label,
# call-args) rows. code-label None means a pure Admiral method.
FILES = {
    "text.admiral": dict(
        var="T",
        doc=["# TEXT - restore the 40x25 text display in the graphics memory",
             "# config. Usage:  T = LOAD(\"TEXT\")(); T.SHOW()"],
        rows=[("SHOW", "TEXT_SHOW", "")],
    ),
    "hires.admiral": dict(
        var="H",
        doc=["# HIRES - mono 320x200 hi-res bitmap (needs REBOOT(TRUE) first).",
             "#   H = LOAD(\"HIRES\")()",
             "#   H.SHOW()           switch VIC to hi-res (builds row table $FF40)",
             "#   H.COLOR(FG=1, BG=6)   fg / bg per 8x8 cell",
             "#   H.PLOT(X=160, Y=100)   set a pixel (x 0..319, y 0..199)",
             "#   H.CLEAR()          clear the bitmap (CLS is a reserved word)",
             "# Generated by tools/gfx_pack.py from tools/gfx.asm."],
        rows=[("SHOW", "HIRES_SHOW", ""),
              ("CLEAR", "GFX_CLS", ""),
              ("COLOR", "HIRES_COLOR", "FG, BG"),
              ("PLOT", "HIRES_PLOT", "X, Y")],
        extra=[("DRAW", HIRES_DRAW)],  # H.DRAW(X0=,Y0=,X1=,Y1=)
    ),
    "mc.admiral": dict(
        var="M",
        doc=["# MC - multicolor 160x200 bitmap (needs REBOOT(TRUE) first).",
             "#   M = LOAD(\"MC\")()",
             "#   M.SHOW()                switch VIC to multicolor",
             "#   M.COLOR(C01=.., C10=.., C11=..)  ink colors (00 = bg $D021)",
             "#   M.PLOT(X=80, Y=100, INK=2)   fat pixel (x 0..159, ink 0..3)",
             "#   M.CLEAR()               clear the bitmap (CLS is reserved)",
             "# Generated by tools/gfx_pack.py from tools/gfx.asm."],
        rows=[("SHOW", "MC_SHOW", ""),
              ("CLEAR", "GFX_CLS", ""),
              ("COLOR", "MC_COLOR", "C01, C10, C11"),
              ("PLOT", "MC_PLOT", "X, Y, INK")],
        extra=[("DRAW", MC_DRAW)],  # M.DRAW(X0=,Y0=,X1=,Y1=,INK=)
    ),
}


def assemble():
    os.makedirs(OUTDIR, exist_ok=True)
    r = subprocess.run(["java", "-jar", KICK, "-odir", OUTDIR, "-vicesymbols", SRC],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(r.stdout + r.stderr)
    syms = {}
    for line in open(os.path.join(OUTDIR, "gfx.vs")):
        m = re.match(r"al C:([0-9a-fA-F]+) \.(\w+)", line.strip())
        if m:
            syms[m.group(2)] = int(m.group(1), 16)
    data = open(os.path.join(OUTDIR, "gfx.prg"), "rb").read()
    load, code = data[0] | (data[1] << 8), data[2:]

    def bytes_of(label):
        end = END.get(label, label + "_END")
        return code[syms[label] - load: syms[end] - load]
    return bytes_of


def esc(b):
    return "".join("\\x%02X" % x for x in b)


def gen(bytes_of):
    for fname, spec in FILES.items():
        out = list(spec["doc"]) + [""]
        var = spec["var"]
        out.append(f"{var} = <>")
        for method, label, _ in spec["rows"]:
            out.append(f'{var}["_{method}"] = "{esc(bytes_of(label))}"')
        for method, label, args in spec["rows"]:
            call = f"CALL(ME._{method}" + (", " + args if args else "") + ")"
            out.append(f'{var}["{method}"] = "{call}"')
        for method, body in spec.get("extra", []):
            out.append(f'{var}["{method}"] = "{body.replace(chr(10), chr(92) + "n")}"')
        out.append(f"RETURN {var}")
        out.append("")
        path = os.path.join(EXAMPLES, fname)
        open(path, "w").write("\n".join(out))
        print(f"wrote {path}")


if __name__ == "__main__":
    gen(assemble())
