#!/usr/bin/env python3
"""Assemble tools/gfx.asm with KickAssembler and generate the graphics-mode
extension libraries examples/{text,hires,mc}.admiral, embedding each routine's
machine code as a \\xNN CALL string.

Each routine in gfx.asm is delimited by its label and a matching <NAME>_END
label. Run after editing gfx.asm:  python3 tools/gfx_pack.py
"""
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KICK = os.path.join(os.path.expanduser("~"), "bin", "KickAssembler", "KickAss.jar")
SRC = os.path.join(ROOT, "tools", "gfx.asm")
OUTDIR = os.path.join(ROOT, "build")
EXAMPLES = os.path.join(ROOT, "examples")

# (label, end-label) — end defaults to label + "_END".
END = {"GFX_CLS": "GFX_CLS_END"}

# Per output file: header comment, dict var, and the (method, code-label,
# call-args) rows. All graphics primitives are native asm — line drawing in
# Admiral-level code is far too slow for a 1 MHz 6510.
FILES = {
    "text.admiral": dict(
        var="T",
        doc=["# TEXT - restore the 40x25 text display in the graphics memory",
             "# config. Usage:  T = LOAD(\"TEXT\")(); T.SHOW()"],
        rows=[("SHOW", "TEXT_SHOW", "")],
    ),
    "hires.admiral": dict(
        var="H",
        doc=["# HIRES - mono 320x200 hi-res bitmap (needs BITMAP(TRUE) first).",
             "#   H = LOAD(\"HIRES\")()",
             "#   H.SHOW()           switch VIC to hi-res (builds row table $FF40)",
             "#   H.COLOR(FG=1, BG=6)   fg / bg per 8x8 cell",
             "#   H.PLOT(X=160, Y=100)   set a pixel (x 0..319, y 0..199)",
             "#   H.CLEAR()          clear the bitmap (CLS is a reserved word)",
             "#   H.TEXT(COL=5, ROW=3, S=\"HELLO\")  draw text (charset 0)",
             "# Generated by tools/gfx_pack.py from tools/gfx.asm."],
        rows=[("SHOW", "HIRES_SHOW", ""),
              ("CLEAR", "GFX_CLS", ""),
              ("COLOR", "HIRES_COLOR", "FG, BG"),
              ("PLOT", "HIRES_PLOT", "X, Y"),
              ("DRAW", "HIRES_DRAW", "X0, Y0, X1, Y1"),
              ("TEXT", "HIRES_TEXT", "COL, ROW, S")],
    ),
    "mc.admiral": dict(
        var="M",
        doc=["# MC - multicolor 160x200 bitmap (needs BITMAP(TRUE) first).",
             "#   M = LOAD(\"MC\")()",
             "#   M.SHOW()                switch VIC to multicolor",
             "#   M.COLOR(C01=.., C10=.., C11=..)  ink colors (00 = bg $D021)",
             "#   M.PLOT(X=80, Y=100, INK=2)   fat pixel (x 0..159, ink 0..3)",
             "#   M.CLEAR()               clear the bitmap (CLS is reserved)",
             "#   M.TEXT(COL=5, ROW=3, S=\"HI\", INK=2, BG=0)  draw text",
             "# Generated by tools/gfx_pack.py from tools/gfx.asm."],
        rows=[("SHOW", "MC_SHOW", ""),
              ("CLEAR", "GFX_CLS", ""),
              ("COLOR", "MC_COLOR", "C01, C10, C11"),
              ("PLOT", "MC_PLOT", "X, Y, INK"),
              ("DRAW", "MC_DRAW", "X0, Y0, X1, Y1, INK"),
              ("TEXT", "MC_TEXT", "COL, ROW, S, INK, BG")],
    ),
}


def assemble():
    os.makedirs(OUTDIR, exist_ok=True)
    r = subprocess.run(["java", "-jar", KICK, "-odir", OUTDIR, "-vicesymbols", SRC],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(r.stdout + r.stderr)
    syms = {}
    for line in open(os.path.join(OUTDIR, "gfx.vs")):
        m = re.match(r"al C:([0-9a-fA-F]+) \.(\w+)", line.strip())
        if m:
            syms[m.group(2)] = int(m.group(1), 16)
    data = open(os.path.join(OUTDIR, "gfx.prg"), "rb").read()
    load, code = data[0] | (data[1] << 8), data[2:]

    def bytes_of(label):
        end = END.get(label, label + "_END")
        return code[syms[label] - load: syms[end] - load]
    return bytes_of


def esc(b):
    return "".join("\\x%02X" % x for x in b)


def gen(bytes_of):
    for fname, spec in FILES.items():
        out = list(spec["doc"]) + [""]
        var = spec["var"]
        out.append(f"{var} = <>")
        for method, label, _ in spec["rows"]:
            # CODE(...) wraps the byte literal as TYPE_CODE so the slot is
            # directly callable: ME._PLOT(X, Y) JSRs the payload.
            out.append(f'{var}["_{method}"] = CODE("{esc(bytes_of(label))}")')
        for method, label, args in spec["rows"]:
            # Direct call (no CALL builtin). `RETURN NONE` after the primitive
            # keeps side-effect methods from auto-printing the W0 return value
            # AND renders nicely when the wrapper itself is auto-printed.
            call = f"ME._{method}(" + args + ")\\nRETURN NONE"
            out.append(f'{var}["{method}"] = "{call}"')
        out.append(f"RETURN {var}")
        out.append("")
        path = os.path.join(EXAMPLES, fname)
        open(path, "w").write("\n".join(out))
        print(f"wrote {path}")


if __name__ == "__main__":
    gen(assemble())
