// Auto-generated by tools/build_tst.py — do not edit by hand.
// Builtin-name TST: 6502 walks the input string right-to-left, so
// names were inserted with characters in reversed order. Sentinel 0
// = no child (root is at index 0; root is never anyone's child).

// 104 nodes, 33 payloads

tst_char:
    .byte $52, $45, $44, $43, $54, $45, $47, $52, $49, $41, $4F, $4C, $4E, $52, $4F, $56, $4B, $47, $4E, $41, $52, $4F, $50, $50, $59, $54, $41, $53, $4D, $4C, $4B, $45, $45, $50, $4F, $4F, $42, $52, $45, $4D, $50, $4E, $45, $4C, $4D, $43, $49, $48, $43, $44, $54, $50, $4F, $53, $52, $55, $43, $45, $52, $53, $54, $53, $4C, $42, $41, $41, $42, $4F, $4C, $47, $43, $4F, $4C, $45, $41, $4D, $52, $4F, $46, $4F, $4C, $46, $47, $57, $53, $57, $52, $49, $44, $45, $4E, $49, $4F, $53, $55, $50, $4E, $49, $58, $45, $48, $59, $45, $4B
tst_lt:
    .byte 1, 2, 3, 0, 0, 0, 0, 8, 9, 0, 0, 0, 0, 0, 0, 16, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 29, 30, 0, 0, 0, 0, 0, 0, 0, 38, 0, 0, 41, 0, 0, 0, 0, 0, 47, 0, 0, 0, 51, 52, 0, 0, 0, 0, 0, 0, 0, 0, 61, 0, 63, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 74, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 87, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
tst_eq:
    .byte 46, 15, 7, 4, 5, 6, 0, 14, 0, 10, 11, 0, 13, 0, 0, 26, 21, 18, 19, 20, 0, 22, 0, 24, 25, 0, 27, 0, 37, 34, 31, 32, 33, 0, 35, 36, 0, 0, 39, 0, 44, 42, 43, 0, 45, 0, 49, 48, 0, 0, 59, 57, 53, 54, 55, 56, 0, 58, 0, 0, 73, 62, 65, 64, 0, 66, 67, 68, 69, 0, 71, 72, 0, 82, 75, 76, 77, 78, 0, 80, 81, 0, 83, 0, 85, 0, 92, 88, 89, 0, 91, 0, 93, 0, 95, 96, 97, 0, 99, 100, 0, 102, 103, 0
tst_gt:
    .byte 60, 28, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 98, 0, 0, 0, 0, 0, 70, 0, 0, 0, 0, 0, 0, 86, 0, 79, 0, 0, 0, 0, 0, 0, 84, 0, 0, 0, 94, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 101, 0, 0, 0, 0, 0
tst_payload:
    .byte 0, 0, 0, 0, 0, 0, 28, 0, 11, 0, 0, 27, 0, 16, 6, 0, 0, 0, 0, 0, 2, 0, 33, 0, 0, 7, 0, 26, 0, 0, 0, 0, 0, 32, 0, 0, 3, 24, 0, 17, 0, 0, 0, 1, 0, 12, 0, 0, 5, 25, 0, 0, 0, 0, 0, 0, 22, 0, 14, 10, 0, 0, 0, 0, 4, 0, 0, 0, 0, 18, 0, 0, 19, 0, 0, 0, 0, 0, 23, 0, 0, 9, 0, 21, 0, 20, 0, 0, 0, 31, 0, 8, 0, 15, 0, 0, 0, 30, 0, 0, 13, 0, 0, 29

// payload index is 1-based (0 reserved for non-terminals); subtract 1
// before reading these tables.
tst_impl_lo:
    .byte <builtin_len, <builtin_range, <builtin_bool, <builtin_abs, <builtin_chr, <builtin_ord, <builtin_type, <builtin_int, <builtin_float, <builtin_str, <builtin_id, <builtin_cmp, <builtin_hex, <builtin_repr, <builtin_sort, <builtin_rnd, <builtin_mem, <builtin_globals, <builtin_locals, <builtin_wset, <builtin_wget, <builtin_cursor, <builtin_format, <builtin_rm, <builtin_dir, <builtin_save, <builtin_load, <builtin_getc, <builtin_key, <builtin_input, <builtin_edit, <builtin_peek, <builtin_poke
tst_impl_hi:
    .byte >builtin_len, >builtin_range, >builtin_bool, >builtin_abs, >builtin_chr, >builtin_ord, >builtin_type, >builtin_int, >builtin_float, >builtin_str, >builtin_id, >builtin_cmp, >builtin_hex, >builtin_repr, >builtin_sort, >builtin_rnd, >builtin_mem, >builtin_globals, >builtin_locals, >builtin_wset, >builtin_wget, >builtin_cursor, >builtin_format, >builtin_rm, >builtin_dir, >builtin_save, >builtin_load, >builtin_getc, >builtin_key, >builtin_input, >builtin_edit, >builtin_peek, >builtin_poke
