// Auto-generated by tools/build_tst.py — do not edit by hand.
// Builtin-name TST: 6502 walks the input string right-to-left, so
// names were inserted with characters in reversed order. Sentinel 0
// = no child (root is at index 0; root is never anyone's child).

// 102 nodes, 32 payloads

tst_char:
    .byte $72, $6C, $64, $63, $74, $65, $67, $72, $69, $61, $6F, $6C, $6E, $72, $6F, $65, $70, $67, $6E, $61, $72, $79, $74, $76, $61, $73, $6C, $6F, $72, $63, $73, $6F, $6F, $62, $6E, $6D, $65, $6D, $72, $65, $6C, $70, $6D, $63, $6F, $68, $63, $69, $64, $73, $72, $75, $63, $74, $70, $65, $72, $73, $74, $73, $6C, $62, $61, $61, $62, $6F, $6C, $67, $63, $6F, $6C, $65, $61, $6D, $72, $6F, $66, $6F, $6C, $66, $67, $77, $73, $77, $72, $69, $64, $65, $6E, $69, $6F, $73, $75, $70, $6E, $69, $78, $65, $68, $79, $65, $6B
tst_lt:
    .byte 1, 2, 3, 0, 0, 0, 0, 8, 9, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 45, 0, 0, 0, 0, 0, 0, 0, 0, 54, 0, 0, 0, 0, 59, 0, 61, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 85, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
tst_eq:
    .byte 44, 26, 7, 4, 5, 6, 0, 14, 0, 10, 11, 0, 13, 0, 0, 16, 21, 18, 19, 20, 0, 22, 0, 24, 25, 0, 27, 28, 29, 30, 0, 32, 33, 0, 39, 36, 37, 0, 0, 40, 0, 42, 43, 0, 49, 46, 0, 48, 0, 50, 51, 52, 0, 57, 55, 56, 0, 0, 71, 60, 63, 62, 0, 64, 65, 66, 67, 0, 69, 70, 0, 80, 73, 74, 75, 76, 0, 78, 79, 0, 81, 0, 83, 0, 90, 86, 87, 0, 89, 0, 91, 0, 93, 94, 95, 0, 97, 98, 0, 100, 101, 0
tst_gt:
    .byte 58, 34, 15, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 41, 0, 38, 0, 0, 0, 0, 0, 0, 0, 53, 47, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 0, 0, 68, 0, 0, 0, 0, 0, 0, 84, 0, 77, 0, 0, 0, 0, 0, 0, 82, 0, 0, 0, 92, 88, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99, 0, 0, 0, 0, 0
tst_payload:
    .byte 0, 0, 0, 0, 0, 0, 29, 0, 11, 0, 0, 28, 0, 16, 6, 0, 0, 0, 0, 0, 2, 0, 7, 0, 0, 27, 0, 0, 0, 0, 23, 0, 0, 3, 0, 0, 0, 17, 25, 0, 1, 0, 0, 12, 0, 0, 5, 0, 26, 0, 0, 0, 22, 0, 0, 0, 14, 10, 0, 0, 0, 0, 4, 0, 0, 0, 0, 18, 0, 0, 19, 0, 0, 0, 0, 0, 24, 0, 0, 9, 0, 21, 0, 20, 0, 0, 0, 32, 0, 8, 0, 15, 0, 0, 0, 31, 0, 0, 13, 0, 0, 30

// payload index is 1-based (0 reserved for non-terminals); subtract 1
// before reading these tables.
tst_impl_lo:
    .byte <builtin_len, <builtin_range, <builtin_bool, <builtin_abs, <builtin_chr, <builtin_ord, <builtin_type, <builtin_int, <builtin_float, <builtin_str, <builtin_id, <builtin_cmp, <builtin_hex, <builtin_repr, <builtin_sort, <builtin_rnd, <builtin_mem, <builtin_globals, <builtin_locals, <builtin_wset, <builtin_wget, <builtin_cursor, <builtin_scroll, <builtin_format, <builtin_rm, <builtin_dir, <builtin_save, <builtin_load, <builtin_getc, <builtin_key, <builtin_input, <builtin_edit
tst_impl_hi:
    .byte >builtin_len, >builtin_range, >builtin_bool, >builtin_abs, >builtin_chr, >builtin_ord, >builtin_type, >builtin_int, >builtin_float, >builtin_str, >builtin_id, >builtin_cmp, >builtin_hex, >builtin_repr, >builtin_sort, >builtin_rnd, >builtin_mem, >builtin_globals, >builtin_locals, >builtin_wset, >builtin_wget, >builtin_cursor, >builtin_scroll, >builtin_format, >builtin_rm, >builtin_dir, >builtin_save, >builtin_load, >builtin_getc, >builtin_key, >builtin_input, >builtin_edit
