// Auto-generated by tools/build_tst.py — do not edit by hand.
// Builtin-name TST: 6502 walks the input string right-to-left, so
// names were inserted with characters in reversed order. Sentinel 0
// = no child (root is at index 0; root is never anyone's child).

// 129 nodes, 43 payloads

tst_char:
    .byte $50, $47, $45, $44, $43, $54, $45, $47, $49, $41, $4F, $4C, $52, $4E, $52, $4F, $44, $4F, $43, $50, $4B, $47, $4E, $41, $52, $4F, $50, $59, $54, $56, $41, $53, $4F, $4C, $4E, $4C, $4B, $45, $45, $50, $4F, $4C, $41, $43, $4F, $42, $4D, $52, $45, $4D, $41, $54, $41, $49, $45, $4C, $53, $58, $4D, $43, $45, $54, $53, $52, $4F, $49, $48, $43, $44, $53, $52, $55, $43, $54, $50, $45, $52, $53, $42, $41, $4F, $4C, $41, $43, $42, $4F, $4C, $47, $4F, $4C, $43, $41, $4F, $4D, $52, $4F, $46, $4C, $46, $52, $49, $45, $53, $47, $57, $57, $44, $45, $4F, $4E, $49, $4F, $42, $45, $52, $4F, $53, $51, $53, $55, $50, $4E, $49, $58, $45, $48, $59, $45, $4B
tst_lt:
    .byte 1, 2, 3, 4, 0, 0, 0, 0, 9, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 20, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 36, 0, 0, 0, 0, 41, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0, 0, 0, 54, 0, 0, 0, 58, 0, 0, 0, 62, 63, 0, 65, 66, 0, 0, 0, 0, 0, 0, 0, 74, 0, 0, 0, 0, 0, 0, 81, 0, 0, 84, 0, 0, 0, 0, 0, 0, 0, 0, 93, 0, 0, 0, 0, 0, 0, 100, 101, 0, 103, 0, 0, 0, 0, 0, 109, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
tst_eq:
    .byte 57, 32, 16, 8, 5, 6, 7, 0, 0, 10, 11, 0, 15, 14, 0, 0, 17, 18, 0, 27, 25, 22, 23, 24, 0, 26, 0, 28, 0, 30, 31, 0, 33, 0, 50, 40, 37, 38, 39, 0, 44, 42, 43, 0, 45, 0, 47, 0, 49, 0, 51, 52, 0, 56, 55, 0, 0, 60, 59, 0, 0, 91, 78, 64, 69, 68, 67, 0, 0, 70, 71, 72, 0, 77, 75, 76, 0, 0, 79, 0, 90, 82, 83, 88, 85, 86, 87, 0, 89, 0, 0, 92, 97, 94, 95, 96, 0, 98, 0, 115, 106, 102, 105, 104, 0, 0, 107, 0, 111, 110, 0, 112, 113, 114, 0, 116, 0, 118, 0, 120, 121, 122, 0, 124, 125, 0, 127, 128, 0
tst_gt:
    .byte 61, 34, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 19, 0, 0, 29, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 53, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 123, 0, 0, 73, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99, 0, 0, 0, 0, 0, 0, 0, 119, 108, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 117, 0, 0, 0, 0, 0, 0, 0, 126, 0, 0, 0, 0, 0
tst_payload:
    .byte 0, 0, 0, 0, 0, 0, 0, 28, 11, 0, 0, 27, 0, 0, 16, 6, 0, 0, 35, 0, 0, 0, 0, 0, 2, 0, 33, 0, 7, 0, 0, 26, 0, 38, 0, 0, 0, 0, 0, 32, 0, 0, 0, 34, 0, 3, 0, 24, 0, 17, 0, 42, 43, 0, 0, 1, 40, 0, 0, 12, 37, 0, 0, 0, 0, 0, 0, 5, 25, 0, 0, 0, 22, 0, 0, 0, 14, 10, 0, 4, 0, 0, 0, 0, 0, 0, 0, 18, 0, 19, 41, 0, 0, 0, 0, 0, 23, 0, 9, 0, 0, 0, 0, 0, 21, 20, 0, 31, 0, 0, 8, 0, 0, 0, 36, 0, 15, 0, 39, 0, 0, 0, 30, 0, 0, 13, 0, 0, 29

// payload index is 1-based (0 reserved for non-terminals); subtract 1
// before reading these tables.
tst_impl_lo:
    .byte <builtin_len, <builtin_range, <builtin_bool, <builtin_abs, <builtin_chr, <builtin_ord, <builtin_type, <builtin_int, <builtin_float, <builtin_str, <builtin_id, <builtin_cmp, <builtin_hex, <builtin_repr, <builtin_sort, <builtin_rnd, <builtin_mem, <builtin_globals, <builtin_locals, <builtin_wset, <builtin_wget, <builtin_cursor, <builtin_format, <builtin_rm, <builtin_dir, <builtin_save, <builtin_load, <builtin_getc, <builtin_key, <builtin_input, <builtin_edit, <builtin_peek, <builtin_poke, <builtin_call, <builtin_code, <builtin_reboot, <builtin_exp, <builtin_log, <builtin_sqrt, <builtin_sin, <builtin_cos, <builtin_tan, <builtin_atan
tst_impl_hi:
    .byte >builtin_len, >builtin_range, >builtin_bool, >builtin_abs, >builtin_chr, >builtin_ord, >builtin_type, >builtin_int, >builtin_float, >builtin_str, >builtin_id, >builtin_cmp, >builtin_hex, >builtin_repr, >builtin_sort, >builtin_rnd, >builtin_mem, >builtin_globals, >builtin_locals, >builtin_wset, >builtin_wget, >builtin_cursor, >builtin_format, >builtin_rm, >builtin_dir, >builtin_save, >builtin_load, >builtin_getc, >builtin_key, >builtin_input, >builtin_edit, >builtin_peek, >builtin_poke, >builtin_call, >builtin_code, >builtin_reboot, >builtin_exp, >builtin_log, >builtin_sqrt, >builtin_sin, >builtin_cos, >builtin_tan, >builtin_atan
